# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:3.8-slim

#SHELL ["/bin/bash", "-c"] 

EXPOSE 8081

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

# Install pip requirements
COPY requirements.txt .
RUN python -m pip install -r requirements.txt

WORKDIR /app
COPY . /app

RUN apt-get update && apt-get -y install sudo
#COPY ../elastic_tmp /app/elastic_tmp
#RUN dpkg -i /app/metricbeat-8.1.3-arm64.deb

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-python-configure-containers
#RUN adduser -u 5678 --disabled-password --gecos "" appuser && adduser appuser sudo && chown -R appuser /app
#USER appuser

# During debugging, this entry point will be overridden. For more information, please refer to https://aka.ms/vscode-docker-python-debug
CMD ["gunicorn", "--reload", "--bind", "0.0.0.0:8081", "app:app"]
